import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Light mode (Architectural Precision)
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "primary-fixed": "#dae2fd",
        "tertiary-fixed-dim": "#c6c7c6",
        "on-secondary-fixed-variant": "#76330d",
        "tertiary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#351000",
        "surface-container": "#e6eeff",
        secondary: "#944a23",
        background: "#f8f9ff",
        primary: "#000000",
        "on-error-container": "#93000a",
        "on-surface-variant": "#45464d",
        "secondary-fixed-dim": "#ffb693",
        "on-tertiary-fixed-variant": "#454747",
        "secondary-fixed": "#ffdbcc",
        "secondary-container": "#fd9e70",
        "inverse-surface": "#233144",
        outline: "#76777d",
        "surface-container-highest": "#d5e3fc",
        "on-tertiary-container": "#838483",
        "inverse-on-surface": "#eaf1ff",
        "inverse-primary": "#bec6e0",
        surface: "#f8f9ff",
        "surface-container-high": "#dce9ff",
        "on-primary-container": "#7c839b",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "on-surface": "#0d1c2e",
        "surface-container-low": "#eff4ff",
        "error-container": "#ffdad6",
        "surface-dim": "#ccdbf3",
        "tertiary-container": "#1a1c1c",
        error: "#ba1a1a",
        "surface-variant": "#d5e3fc",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-tint": "#565e74",
        tertiary: "#000000",
        "on-background": "#0d1c2e",
        "outline-variant": "#c6c6cd",
        "on-secondary-container": "#76340e",
        "surface-bright": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "primary-container": "#131b2e",
        "on-primary-fixed-variant": "#3f465c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "section-gap": "120px",
        "margin-mobile": "20px",
        gutter: "24px",
        base: "8px",
        "container-max": "1280px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "500" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
